### ISSUE TITLE
License Clarification, referenced DocX.dll is not "MIT licensed"

### ISSUE THREAD

**Issue by trianglePB** [iAJTin/iExportEngine#1]
It seems that your code has a dependency on  https://github.com/xceedsoftware/DocX, which states to be under the "Xceed Software, Inc. Community License." (https://github.com/xceedsoftware/DocX/blob/master/license.md)
The license makes clear that it for non-commercial use only (and offers a commercial license can be purchased)
I think you should at least mention this. It might even be the case that you cannot include the mentioned library in your release without mentioning this, maybe it is even violating the license if you provide it unter the MIT license - I'm not sure.

**Comment by iAJTin** [comment]
Hello, you are indeed right that DocX was acquired by the company Xceed Software, Inc.

But there is a nuance, this company has a branch for its commercial product and another branch for the classic product (the one in question), if the version used is 1.0.0.13 (classic), and everything that is not is supported by that version, it has been done in the project to get around that problem.

In any case, I leave you a link where another user makes a query about the license (https://github.com/xceedsoftware/DocX/issues/424)

I hope the answer will help you

Greetings!(Edi
